### ISSUE TITLE
API: Make config path relative to the config loader

### ISSUE THREAD

**Issue by jeyemwey** [sipgate/gnt-cc#10]
Since I used it tonight for my uni project: [There is a way to load a file relatively to the code file](https://stackoverflow.com/a/17072096/3944068). We should use this for the config loader, and so untangle the relative path issue.

```go
import "filepath"
// ... among others

path, err := filepath.Abs("../") // /api folder then, even if called from a test
if err != nil {
	panic(fmt.Errorf("Fatal error config file: %s", err))
}
viper.AddConfigPath(path)
```

**Comment by geigi** [comment]
Nice :)

**Comment by paulschwoerer** [comment]
I think this might currently not be needed, as config loading was restructured a while ago. Let's keep it in mind though

Closing for now
