### ISSUE TITLE
Job watcher isn't cluster aware

### ISSUE THREAD

**Issue by geigi** [sipgate/gnt-cc#51]
Scenario: Shutdown a VM and then switch the ganeti cluster. Clicking on the job in the watcher now tries to open the job in the currently selected cluster instead of the cluster, where the job was initiated.

Expected behaviour: The job watcher should be cluster aware. It should display the cluster, where the job is running. Also clicking on the job should jump to the correct cluster.

**Comment by paulschwoerer** [comment]
fixed in #62
